#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 27 13:13:17 2016

Exercise 2 from Introduction to Computational Thinking and Data Science

@author: Ronaldo S.A. Batista
"""

# this function generates all combinations of N items using the itertools 
# package from python.
# The number of combinations generated by N items in one bag is 2**N
# For instance: 
#   powerSet([1,2,3]) --> (), (1,),(2,), (3,), (1,2), (2,3), (1,3), (1,2,3) 

from itertools import chain, combinations

def powerSet(iterable):
    
    #make a list from the iterable
    items = list(iterable)
    
    return chain.from_iterable(combinations(items, k)\
    for k in range(len(items) + 1))
    
    
comb = powerSet(['a','b','c','d'])

for item in comb:
    print (item)